---
# samba4_ad_client_sssd/tasks/configure_sssd.yml

- name: 'Create /etc/sssd/sssd.conf'
  ansible.builtin.template:
    src: 'etc_sssd_sssd.conf.j2'
    dest: '/etc/sssd/sssd.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify:
    'Restart SSSD service'
