---
# samba4_ad_client_sssd/tasks/main.yml

- name: "Load variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution }}.yml"
    - "vars_{{ ansible_os_family }}.yml"

- name: 'Install packages'
  include_tasks: install_packages.yml

- name: 'Configure SSSD'
  include_tasks: configure_sssd.yml

- name: 'Enable the SSSD service'
  include_tasks: enable_sssd_service.yml
